#启用默认配置文件
profile:
management.endpoint.env.enabled: false
spring.profiles:
 active:
  - ${profile}
server:
  port: 8083
  
spring.application.name: partner
spring.main.allow-bean-definition-overriding: true

logging.config: classpath:log4j2-dev.xml


#eureka
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 100000
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 50000
    instanceInfoReplicationIntervalSeconds: 50000
    initialInstanceInfoReplicationIntervalSeconds: 50000
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/


#数据源
spring.datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  druid:
    # mysql环境配置项
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dccp_dev?characterEncoding=UTF-8&characterSetResults=UTF-8&useUnicode=false&useSSL=false&useAffectedRows=true&serverTimezone=GMT%2B8
    username: root
    password: 'am6375'
    validation-query: SELECT 1
    initial-size: 10  # 初始化大小，最小，最大 
    min-idle: 10
    max-active: 200
    max-wait: 60000  # 配置获取连接等待超时的时间
    time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false  # 关闭PSCache，并且指定每个连接上PSCache的大小
    filter:   #是否启用StatFilter默认值true
      stat:
        log-slow-sql: true
web-stat-filter:
  enabled: true
  url-pattern:  "/*"
  exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,*.woff,/swagger-resources/*,/swagger-ui.html"
  session-stat-enable: true #session统计功能
  session-stat-max-count: 100000 #最大session数

stat-view-servlet:  #配置StatViewServlet
  enabled: true
  login-username: login-username
  login-password: login-password
  url-pattern: "/druid/*"
  reset-enable: true

mybatis:
  mapper-locations: classpath*:com/ysgj/**/mysql/*.xml
  type-aliases-package: com.ysgj.*.entity
  executorType: BATCH 




      



   







